---
title: "Experience"
---

---


## PhD Mechanical Engineering
_2022 — present_ · **University College London**

Investigating ultrasound-assisted additive manufacturing (AM) utilising in situ synchrotron radiography at ESRF and Diamond Light Source. Supervised by Peter Lee, Alex Leung, and Andrew Kao and co-sponsored by Rolls-Royce plc. and the Engineering and Physical Sciences Research Council (EPSRC).

- _In situ_ synchrotron X-ray imaging of AM processes
- Development of an _in situ_ process replicator to enable novel experiments
- Collaboration with international partners on research. A particular highlight was coordinating a session of the AM block allocation group at ESRF

**Placements**
<div style="margin-left: 3rem;">
<details>
<summary>
**2023-2025** · Postgraduate Teaching Assistant · University College London, Mechanical ENgineering Department
</summary>
Teaching assistant for two master's level modules: Materials and fatigue, and Advanced Characterisation & Laboratory Techniques.

- 2024/5: runner-up for Mechanical Engineering PGTA awards - Best feedback
- 2023/4: nominated for Mechanical Engineering PGTA awards - Best student Engagement
</details>
</div>
<div style="margin-left: 3rem;">
<details>
<summary>
**Summer 2025** · Policy Advisor - Net Zero Innovation · Department for Energy Security and Net Zero, UK Government
</summary>

Policy advisor focusing on the UK's scaleup problems for net zero technologies, particularly in the context of the Net Zero Innovation Portfolio (NZIP).

- Providing case studies on NZIP alumni and their scaleup challenges to inform novel scaleup support policies
- Contributed to assessment on technological development in the UK across different sectors
</details>
</div>

---

## MEng Materials Science
_2018 — 2022_ · **University of Oxford**

Integrated MEng in Materials Science, with a focus on metallurgy. Supervised by David Armstrong and Peter Nellist.

- Thesis on liquid lithium corrosion for nuclear fusion applications
- Modules covering Advanced Alloys, Energy Materials, Nanomaterials amongst others


**Placements**
<div style="margin-left: 3rem;">
<details>
<summary>
**Summer 2019** · Computational Modelling Intern · Interdisciplinary Centre for Advanced Materials Simulation, Ruhr Universitat Bochum
</summary>

Computational modelling of interstitial defects in iron for radiation damage studies using atomistic modelling. 

- Comparison of interatomic potentials for iron and their effect on defect formation energies
</details>
</div>